// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "imViewWindowGUI.h"

imViewWindowGUI::imViewWindowGUI() {
  { renderWindow = new Fl_Double_Window(539, 489);
    renderWindow->user_data((void*)(this));
    { m_FlRenderWindowInteractor = new vtkFlRenderWindowInteractor(0, -2, 540, 495);
      m_FlRenderWindowInteractor->box(FL_BORDER_BOX);
      m_FlRenderWindowInteractor->color(FL_BACKGROUND_COLOR);
      m_FlRenderWindowInteractor->selection_color(FL_BACKGROUND_COLOR);
      m_FlRenderWindowInteractor->labeltype(FL_NORMAL_LABEL);
      m_FlRenderWindowInteractor->labelfont(0);
      m_FlRenderWindowInteractor->labelsize(14);
      m_FlRenderWindowInteractor->labelcolor(FL_FOREGROUND_COLOR);
      m_FlRenderWindowInteractor->align(Fl_Align(FL_ALIGN_CENTER));
      m_FlRenderWindowInteractor->when(FL_WHEN_RELEASE);
    } // vtkFlRenderWindowInteractor* m_FlRenderWindowInteractor
    renderWindow->end();
  } // Fl_Double_Window* renderWindow
}

imViewWindowGUI::~imViewWindowGUI() {
  this->Hide();
}

void imViewWindowGUI::Show() {
  renderWindow->show();
  m_FlRenderWindowInteractor->show();
}

void imViewWindowGUI::Hide(void) {
  renderWindow->hide();
}
