// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef imViewWindowGUI_h
#define imViewWindowGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "imViewWindowBase.h"
#include "vtkFlRenderWindowInteractor.h"

class imViewWindowGUI : public imViewWindowBase {
public:
  imViewWindowGUI();
  Fl_Double_Window *renderWindow;
  vtkFlRenderWindowInteractor *m_FlRenderWindowInteractor;
  ~imViewWindowGUI();
  void Show();
  void Hide(void);
};
#endif
